### ISSUE TITLE
Update to 3.0.113-1

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs-freebsd-ports#3]
Hello,

It looks like MooseFS 3.0.113-1 is out per https://github.com/moosefs/moosefs/blob/master/NEWS. Can the FreeBSD ports tree be updated, or the moosefs-freebsd-ports repository?

**Comment by pkonopelko** [comment]
Actually it is not out yet, there are a few more changes that will be committed to 3.0.113. Once it is ready, appropriate [tag](https://github.com/moosefs/moosefs/releases) will be added.

**Comment by jSML4ThWwBID69YC** [comment]
Ahhh, my mistake. Sorry for the noise.

**Comment by pkonopelko** [comment]
Since MooseFS 3.0.113 is [released](https://github.com/moosefs/moosefs/releases/tag/v3.0.113), I opened a bug in order to update the FreeBSD ports tree with the latest version. Please find a link to the bug for your reference:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246416

**Comment by jSML4ThWwBID69YC** [comment]
Thank you.
