### ISSUE TITLE
Update to 3.0.114

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [moosefs/moosefs-freebsd-ports#4]
Hello,

Please update the FreeBSD ports version to 3.0.114.

**Comment by pkonopelko** [comment]
Waiting for [this one](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248152) to be accepted first since it already is included in the release (see [this commit](https://github.com/moosefs/moosefs/commit/759598db167768140aa68456494767399ecc2c1a)).

**Comment by jSML4ThWwBID69YC** [comment]
Hello, 

That commit has been accepted. Can the port be updated to 3.0.114?

**Comment by pkonopelko** [comment]
Yes, it will be possible for me to update the ports to 3.0.114 next week. Thank you for your patience.

**Comment by jSML4ThWwBID69YC** [comment]
Ping.

**Comment by jSML4ThWwBID69YC** [comment]
Hello @pkonopelko 

Is there a bug or issue preventing the update?

**Comment by jSML4ThWwBID69YC** [comment]
Ping

**Comment by pkonopelko** [comment]
Hello @jSML4ThWwBID69YC,

Please accept my apologies that you had to wait so long. Thanks a lot for pushing this. I have just uploaded an update for the FreeBSD Ports tree which includes update MooseFS to 3.0.114: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250060.

I believe that with next upcoming release (3.0.115) it will happen much faster. By the way 3.0.115 should be released very soon.

Please keep in mind that you can always install the latest version of MooseFS on FreeBSD at least by two other ways:
1. By using our packages repo: (check out http://get.moosefs.com – please select "FreeBSD"). These packages are built using the ports created in the below way. These ports are consistent with ports that land in official FreeBSD Ports tree.
2. By building the `systutils/moosefs3-*` ports yourself:
    * Clone the MooseFS GitHub repository: `git clone git@github.com:moosefs/moosefs.git`
    * `cd moosefs/freebsd`
    * `mkdir ports`
    * `./makeports.sh ports
    * The ports will be created in `moosefs/freebsd/ports` dir. You can copy them over to `/usr/ports/sysutils` then, and use.

Thanks,
Piotr

**Comment by jSML4ThWwBID69YC** [comment]
Hello, 

I've updated to 3.0.114 successfully. I'll keep the additional instructions in mind for the next update. Thank you.
